services:
  postgres-db:
    image: postgres:17-alpine
    container_name: cinema_rest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: project2_pass
      POSTGRES_DB: cinema_rest_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema_rest_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cinema-network

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinema-java-app:latest
    container_name: cinema-java-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cinema_rest_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: project2_pass
      JAVA_OPTS: "-Xms256m -Xmx512m"
    networks:
      - cinema-network

volumes:
  postgres_data:

networks:
  cinema-network:
    driver: bridge